server:
  port: 8080
mpesa:
  daraja:
    consumer-key: GnAOnXaES6XNGKx0mCqiaUGzEjHFGuJ8
    consumer-secret: HxeBGlCGgwpAUqNz
    grant-type: client_credentials
    oauth-endpoint: https://sandbox.safaricom.co.ke/oauth/v1/generate
    register-url-endpoint: https://sandbox.safaricom.co.ke/mpesa/c2b/v1/registerurl
    simulate-transaction-endpoint: https://sandbox.safaricom.co.ke/mpesa/c2b/v1/simulate
    shortCode: 603024
    confirmationURL: https://96bb83ead560.ngrok.io/mobile-money/confirmation
    validationURL: https://96bb83ead560.ngrok.io/mobile-money/validation
    responseType: Completed